// Expo config plugin: let the Android app trust user-installed CA certificates.
//
// Since API 24 an app trusts only the system CA store and ignores CAs the user
// installed, unlike Chrome, so a station behind a private CA fails with
// "Trust anchor for certification path not found" (#458). This emits a
// network-security-config adding `user` alongside `system`.
//
// Once a networkSecurityConfig exists, Android ignores the manifest's
// `android:usesCleartextTraffic` and governs cleartext from this file instead,
// so `cleartextTrafficPermitted="true"` must stay here or HTTP/LAN stations
// break (#464).
//
// android/ is regenerated by `expo prebuild`, so this file is written on every
// prebuild rather than checked in.
//
// Usage in app.json plugins: "./plugins/withAndroidUserCaTrust"

const { withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidUserCaTrust.js — do not edit by hand. -->
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
            <certificates src="user" />
        </trust-anchors>
    </base-config>
</network-security-config>
`;

// Write res/xml/network_security_config.xml into the prebuilt android project.
function withNetworkSecurityConfigFile(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const xmlDir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml',
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, 'network_security_config.xml'), XML);
      return cfg;
    },
  ]);
}

// Point <application> at the config above.
function withNetworkSecurityConfigManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = cfg.modResults.manifest.application?.[0];
    if (!app) {
      throw new Error('[withAndroidUserCaTrust] <application> not found in AndroidManifest.xml');
    }
    app.$['android:networkSecurityConfig'] = '@xml/network_security_config';
    return cfg;
  });
}

module.exports = function withAndroidUserCaTrust(config) {
  return withNetworkSecurityConfigManifest(withNetworkSecurityConfigFile(config));
};
