// Generates cli/src/assets.generated.ts from the repo-root compose files +
// .env.example — run `npm --prefix cli run embed-assets` after editing those.
// A Bun-compiled binary can't read the repo at runtime, so `subwave init`
// materialises these embedded copies. The output is committed; cli-assets-
// check.yml catches staleness.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '..', '..');
const OUT_FILE = resolve(HERE, '..', 'src', 'assets.generated.ts');

interface Asset {
  name: string; // exported constant name
  source: string; // path relative to the repo root
}

const ASSETS: Asset[] = [
  { name: 'COMPOSE_YML',                source: 'docker-compose.yml' },
  { name: 'COMPOSE_BYO_YML',            source: 'docker-compose.byo.yml' },
  { name: 'COMPOSE_DEV_YML',            source: 'docker-compose.dev.yml' },
  { name: 'COMPOSE_TTS_HEAVY_GPU_YML',  source: 'docker-compose.tts-heavy-gpu.yml' },
  { name: 'COMPOSE_ANALYZER_GPU_YML',   source: 'docker-compose.analyzer-gpu.yml' },
  { name: 'ENV_EXAMPLE',                source: '.env.example' },
];

const banner = `// AUTO-GENERATED by cli/scripts/embed-assets.ts — do not edit by hand.
// Regenerate with: npm --prefix cli run embed-assets
//
// These string constants are the source-of-truth content that
// \`subwave init\` materialises into SUBWAVE_HOME. CI verifies they match
// the original files at the repo root.
`;

// The minimum escape set that round-trips a backtick template exactly. Newlines
// stay literal — they read better in the generated file than `\n` escapes.
function encode(content: string): string {
  return content
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

function main(): void {
  const parts: string[] = [banner, ''];
  for (const a of ASSETS) {
    const abs = resolve(REPO_ROOT, a.source);
    const body = readFileSync(abs, 'utf8');
    parts.push(`// ${a.source}`);
    parts.push(`export const ${a.name} = \`${encode(body)}\`;`);
    parts.push('');
  }
  // Baked in because reading package.json at runtime doesn't survive
  // `bun build --compile`. The trailing `x-release-please-version` marker must
  // stay on the version line: release-please keys off it to bump this file.
  const pkg = JSON.parse(readFileSync(resolve(REPO_ROOT, 'cli', 'package.json'), 'utf8')) as { version: string };
  parts.push('// cli/package.json#version (embedded so the compiled binary can self-identify');
  parts.push('// — used by `subwave --version`).');
  parts.push(`export const CLI_VERSION = \`${encode(pkg.version)}\`; // x-release-please-version`);
  parts.push('');

  writeFileSync(OUT_FILE, parts.join('\n'));
  const sizes = ASSETS.map((a) => {
    const abs = resolve(REPO_ROOT, a.source);
    return `${a.source} (${readFileSync(abs, 'utf8').length} bytes)`;
  });
  process.stdout.write(`embedded ${ASSETS.length} files + CLI_VERSION=${pkg.version} → ${OUT_FILE}\n`);
  for (const s of sizes) process.stdout.write(`  ${s}\n`);
}

main();
