#!/usr/bin/env bash
# SUB/WAVE setup — idempotent, no sudo. Three jobs:
#
#   1. Scaffold a small .env (ADMIN_USER, ADMIN_PASS, SITE_URL, detected TZ) if
#      missing; everything richer is collected by the wizard at /setup.
#   2. Create state/ with the right permissions, host-side, so bind mounts are
#      satisfied without waiting on the icecast healthcheck.
#   3. Generate web/.env.local for native `npm run dev` workflows.
#
# Icecast passwords are generated by the subwave-icecast image on first boot into
# state/icecast-secrets.env; liquidsoap sources that file via its entrypoint.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE_DIR="${STATE_DIR:-$REPO_DIR/state}"
ROOT_ENV="$REPO_DIR/.env"
WEB_ENV_LOCAL="$REPO_DIR/web/.env.local"

say()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }

# Resolve the host's IANA timezone so the DJ announces local time. Without TZ the
# container runs in UTC and time announcements drift by the host's offset (#205).
# Falls back to the compose default, not UTC, when nothing resolves.
detect_tz() {
  if [[ -n "${TZ:-}" ]]; then echo "$TZ"; return; fi
  if [[ -r /etc/timezone ]]; then
    local t; t="$(tr -d '[:space:]' < /etc/timezone)"
    [[ -n "$t" ]] && { echo "$t"; return; }
  fi
  if command -v timedatectl >/dev/null 2>&1; then
    local t; t="$(timedatectl show -p Timezone --value 2>/dev/null)"
    [[ -n "$t" ]] && { echo "$t"; return; }
  fi
  if [[ -L /etc/localtime ]]; then
    # e.g. /usr/share/zoneinfo/Europe/London -> Europe/London
    local t; t="$(readlink /etc/localtime | sed 's#.*/zoneinfo/##')"
    [[ "$t" == */* ]] && { echo "$t"; return; }
  fi
  echo "Europe/London"
}

# 1. State dir
say "Using STATE_DIR=$STATE_DIR"
mkdir -p "$STATE_DIR"
chmod 777 "$STATE_DIR"

# 2. Root .env (3 required vars)
if [[ ! -f "$ROOT_ENV" ]]; then
  ADMIN_PASS="$(openssl rand -hex 16)"
  DETECTED_TZ="$(detect_tz)"
  say "Generating $ROOT_ENV (random ADMIN_PASS — change it later if you like)"
  say "Detected timezone: $DETECTED_TZ (edit TZ in $ROOT_ENV to change)"
  cat > "$ROOT_ENV" <<EOF
# SUB/WAVE — required configuration
# Generated by scripts/setup.sh. Everything else is collected by the web
# wizard at /setup once the stack is up.
ADMIN_USER=admin
ADMIN_PASS=$ADMIN_PASS
SITE_URL=
# Host timezone the DJ announces — auto-detected at scaffold time.
TZ=$DETECTED_TZ
EOF
  chmod 600 "$ROOT_ENV"
else
  say "$ROOT_ENV exists — leaving it alone"
fi

# 3. web/.env.local for native dev (`cd web && npm run dev`).
# Prod runs web behind Caddy where /api and /stream.mp3 are same-origin, so no
# env file is needed. Native dev on :7700 must be told where the controller
# (7701) and Icecast (7702) live, or every /api/* request 404s.
if [[ ! -f "$WEB_ENV_LOCAL" ]]; then
  say "Generating $WEB_ENV_LOCAL for native dev"
  cat > "$WEB_ENV_LOCAL" <<EOF
NEXT_PUBLIC_API_URL=http://localhost:7701
NEXT_PUBLIC_STREAM_URL=http://localhost:7702/stream.mp3
EOF
else
  say "$WEB_ENV_LOCAL exists — leaving it alone"
fi

# Migration helper: an upgrader from the docker/.env + controller/.env layout has
# no Navidrome creds or API keys in the new root .env. Flag that env_file now
# reads ./.env so they can move what they want across.
if [[ -f "$REPO_DIR/controller/.env" ]] || [[ -f "$REPO_DIR/docker/.env" ]]; then
  cat >&2 <<MIGRATE
[!] Detected legacy controller/.env or docker/.env from the pre-single-compose layout.
    They are NOT used anymore — the new compose files load ./.env (root) only.
    If those files have Navidrome creds or LLM API keys you want to keep,
    copy them into ./.env now (or skip and re-enter them in the web wizard).
MIGRATE
fi

cat <<EOF

Setup scaffolded.
  STATE_DIR: $STATE_DIR
  .env:      $ROOT_ENV   (admin creds + SITE_URL)

Next:
  Prod:      docker compose up -d
  BYO proxy: docker compose -f docker-compose.byo.yml up -d
  Dev:       docker compose -f docker-compose.dev.yml up -d

Then visit http://localhost:7700/onboarding to finish configuration
(Navidrome, LLM, TTS, DJ persona, jingles). Or run 'npm run setup' for the
terminal-based equivalent.
EOF
